'use strict';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import-x/no-namespace, import-x/no-unresolved
import * as build from '../build/server';
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

export const onRequest = createPagesFunctionHandler({ build });
