'use strict';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `react-router build`
// eslint-disable-next-line import-x/no-namespace, import-x/no-unresolved
import * as build from '../build/server';
import { createPagesFunctionHandler } from '@react-router/cloudflare';

export const onRequest = createPagesFunctionHandler({
    build
});
