"$schema" = "node_modules/wrangler/config-schema.json"
compatibility_date = "2025-04-02"
name = "ms0503-dev"
pages_build_output_dir = "./build/client"

[observability]
enabled = true

[placement]
mode = "smart"
