#:schema: https://schema.tauri.app/config/2
identifier = "dev.ms0503.ms0503-dev-editor"
product-name = "ms0503-dev-editor"
version = "0.1.0"

[app.security]
csp = ""

[[app.windows]]
height = 600
title = "波打ち際の書斎"
width = 800

[build]
before-build-command = "yarn build"
before-dev-command = "yarn dev"
dev-url = "http://localhost:5173"
frontend-dist = "build/client"

[bundle]
active = true
icon = [
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/32x32.png",
    "icons/icon.icns",
    "icons/icon.ico"
]
targets = [
    "rpm"
]
