"$schema" = "../node_modules/wrangler/config-schema.json"
compatibility_date = "2025-04-02"
name = "ms0503-dev-editor"

[[d1_databases]]
binding = "db"
database_id = "4591e282-92ed-4404-aa80-ba091b2e8eab"
database_name = "ms0503-dev"
