"$schema" = "node_modules/wrangler/config-schema.json"
compatibility_date = "2025-04-02"
compatibility_flags = ["nodejs_compat"]
name = "ms0503-dev"
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "db"
database_id = "4591e282-92ed-4404-aa80-ba091b2e8eab"
database_name = "ms0503-dev"

[observability]
enabled = true

[placement]
mode = "smart"
