"$schema" = "../node_modules/wrangler/config-schema.json"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]
main = "./workers/app.ts"
name = "ms0503-dev"

[assets]
directory = "./build/client"
not_found_handling = "404-page"
run_worker_first = false

[[d1_databases]]
binding = "db"
database_id = "4591e282-92ed-4404-aa80-ba091b2e8eab"
database_name = "ms0503-dev"
migrations_dir = "migrations"

[images]
binding = "img"

[[kv_namespaces]]
binding = "kv"
id = "e5c201a29fe64c18b071fcc91543d719"

[observability]
enabled = true

[placement]
mode = "smart"

[[r2_buckets]]
binding = "obj"
bucket_name = "objects"
